# Generated by Django 4.2.3 on 2023-07-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student1Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu1_name", models.CharField(max_length=100)),
                ("stu1_email", models.EmailField(max_length=254)),
                ("stu1_mobile", models.IntegerField()),
                ("stu1_city", models.CharField(max_length=100)),
            ],
        ),
    ]
